services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alfama_web
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    ports:
      - "8080:80"
    networks:
      - alfama

  db:
    image: mysql:8.0
    container_name: alfama_web_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: alfama
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - alfama

networks:
  alfama:
    driver: bridge

volumes:
  db_data:
